project:
  type: website

website:
  title: "Riding Two Cities"
  navbar:
    left:
      - href: data.qmd
        text: Data & Methods
      - href: aboutme.qmd
        text: About
  search: true

format:
  html:
    toc: true
    toc-location: right
    theme: [darkly, custom.scss]
    
editor: visual

